name: Build server Docker image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker-build-push.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: server
          file: server/Dockerfile
          tags: ghcr.io/matuszelenak/python:3.13-nogil-bookwork-slim
